inv/urls.py
"""inventario URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
Function views

"""
from django.urls import path, include, re_path
from . import views

urlpatterns = [
	path('', views.index, name="index"),
#	path('inventario/asignar', views.asignacion_new, name='asignacion_new'),
	path('inventario/asignar', views.AsignacionNew.as_view(), name='asignacion_new'),
	path('inventario/asignar/list', views.asignacion_list, name='asignacion_list'),
	path('inventario/listado', views.inventario, name='inventario'),
	path('salas/', views.sala_list, name='salas_list'),
	re_path(r'^inventario/objeto/(?P<pk>[0-9]+)/$', views.objeto_detail, name='objeto_detail'),
	re_path(r'^sala/(?P<pk>[0-9]+)/$', views.sala_detail, name='sala_detail'),
	path('chaining/', include("smart_selects.urls")),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

inventario/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('',include('inv.urls')),
    path('admin/', admin.site.urls),
	path('chaining/', include("smart_selects.urls")),
]

nahuelcura/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
	path('',include('inv.urls')),
    path('admin/', admin.site.urls),
]

inv/models.py
from django.db import models
from django.utils import timezone
from smart_selects.db_fields import ChainedForeignKey
from  django.contrib.auth.models import User

#Clases definiendo los objetos inventariados
class Clase(models.Model):
	nombre=models.CharField(max_length=50)
	codigo=models.CharField(max_length=3, null=True, blank=True)
	descripcion=models.TextField(default="")
	
	def __str__(self):
		return self.codigo
	
	def cod(self):
		return self.codigo
		
class Tipo(models.Model):
	clase=models.ForeignKey(Clase, on_delete=models.CASCADE)
	nombre=models.CharField(max_length=50)
	
	def __str__(self):
		return self.nombre

class Objeto(models.Model):
	tipo=models.ForeignKey(Tipo, on_delete=models.CASCADE)
	nombre=models.CharField(max_length=100)

	def __str__(self):
		return self.nombre
		
class Articulo(models.Model):
	objeto=models.ForeignKey(Objeto, on_delete=models.CASCADE)
	codigo=models.CharField(max_length=7)
	nombre=models.TextField(default="")
	estado=models.CharField(max_length=1)
	fecha=models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		return self.nombre
	
#-------------------------------------------------
#Clase de ubicaciones
class Edificio(models.Model):
	nombre=models.CharField(max_length=50)
	descripcion=models.TextField(default="")
	
	def __str__(self):
		return self.nombre
		
class Piso(models.Model):
	edificio=models.ForeignKey(Edificio, on_delete=models.PROTECT)
	nombre=models.CharField(max_length=50)
	
	def __str__(self):
		return "%s - %s"%(self.edificio.nombre,self.nombre)

class Sala(models.Model):
	piso=models.ForeignKey(Piso, on_delete=models.PROTECT)
	nombre=models.CharField(max_length=50)
	uso=models.CharField(max_length=100)
	descripcion=models.TextField(default="")
	
	def __str__(self):
		return "%s - %s"%(self.uso,self.nombre)
	
class Ubicacion(models.Model):
	nombre=models.CharField(max_length=50)
	descripcion=models.CharField(max_length=150)
	  
	class Meta:
		verbose_name_plural="Ubicaciones"
	
	def __str__(self):
		return self.nombre


class Asignacion(models.Model):
	edificio=models.ForeignKey(Edificio, on_delete=models.PROTECT, null=True)
	piso=ChainedForeignKey(
		Piso,
		chained_field='edificio',
		chained_model_field='edificio',
		show_all=False,
		auto_choose=True,
		sort=True,
		null=True)
	sala=ChainedForeignKey(
		Sala,
		chained_field='piso',
		chained_model_field='piso',
		show_all=False,
		auto_choose=True,
		sort=True,
		null=True)
	tipo=models.ForeignKey(Tipo, on_delete=models.PROTECT, null=True)
	objeto=ChainedForeignKey(
		Objeto,
		chained_field='tipo',
		chained_model_field='tipo',
		show_all=False,
		auto_choose=True,
		sort=True,
		null=True)
	cantidad=models.PositiveSmallIntegerField(default=0)
	observaciones=models.TextField(default="", blank=True)
	fecha=models.DateTimeField(default=timezone.now)
	usuario=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	
	class Meta:
		verbose_name_plural="Asignaciones"
		
	def guardar(self):
		self.fecha=timezone.now()
		self.save()


	def __str__(self):
		return '%s - %s - %i'%(self.sala, self.objeto, self.cantidad)
	

class Movimiento(models.Model):
	tipo=models.ForeignKey(Tipo, on_delete=models.PROTECT, null=True)
	objeto=models.ForeignKey(Objeto, on_delete=models.PROTECT, null=True)
	cantidad=models.PositiveSmallIntegerField(default=0)
	origen=models.ForeignKey(Sala, related_name='origen', on_delete=models.PROTECT, null=True)
	destino=models.ForeignKey(Sala, related_name='destino', on_delete=models.PROTECT, null=True)
	usuario=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	fecha=models.DateTimeField(default=timezone.now)

	def guardar(self):
		self.fecha=timezone.now()
		self.save()




	
#class Movimiento(models.Model):
#	objeto=Models.ForeignKey(Objeto, on_delete=models.PROTECT, null=True)

inv/forms.py
from django import forms

from .models import Asignacion

class AsignacionForm(forms.ModelForm):
	
	class Meta:
		model=Asignacion
		fields=('edificio','piso','sala','tipo','objeto','cantidad','observaciones')

inv/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Asignacion, Edificio, Piso, Sala, Tipo, Objeto
from .forms import AsignacionForm
from django.views.generic import TemplateView, CreateView
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
	return render(request, 'index.html')
	
class AsignacionNew(LoginRequiredMixin, CreateView):
	template_name='asignacion_edit.html'
	model=Asignacion
	fields= ['edificio','piso','sala','tipo','objeto','cantidad','observaciones']
	success_url="/inventario/asignar"

	def get_context_data(self, **kwargs):
		context = super(AsignacionNew, self).get_context_data(**kwargs)
		context['edificios']= Edificio.objects.all()
		context['pisos']=Piso.objects.all()
		context['salas']=Sala.objects.all()
		context['tipos']=Tipo.objects.all().order_by('nombre')
		context['objetos']=Objeto.objects.all()
		return context


def asignacion_list(request):
	asignaciones= Asignacion.objects.all().order_by('sala')
	return render(request, 'asignacion_list.html', {'asignaciones':asignaciones})


def inventario(request):
	inventario = Asignacion.objects.values('objeto__nombre','objeto__id').annotate(total=Sum('cantidad')).order_by('objeto__nombre')
	return render(request, 'inventario.html', {'inventario':inventario})

def objeto_detail(request, pk):
	objeto = get_object_or_404(Objeto, pk=pk)
	detalle=Asignacion.objects.filter(objeto=pk).order_by('sala__uso')
	return render(request, 'objeto_detail.html',{'objeto':objeto,'detalle':detalle})

def sala_list(request):
	salas=Sala.objects.all().order_by('uso')
	return render(request, 'salas_list.html', {'salas':salas})

def sala_detail(request, pk):
	sala = get_object_or_404(Sala, pk=pk)
	detalle=Asignacion.objects.filter(sala=pk).order_by('tipo')
	return render(request, 'sala_detail.html',{'sala':sala,'detalle':detalle})

inv/templates/asignacion_edit.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Asignar articulo</h2>
<div class='col-md-8 col-md-offset-2'>
	<form method="POST" role='form'>{% csrf_token %}
	<!-- Fila 1 -->
	<div class="row">
		 <div class="col-md-4">
		 	<div class="col-md-6">Edificios</div>
	        <select name="edificio" id="id_edificio" class="form-control form-control-sm">
	        	<option value="0"> --- </option>
	        	{% for item in edificios %}
	        		<option value="{{ item.id }}">{{ item.nombre }}</option>
	        	{% endfor%}
	        </select>
	    </div>
	
	    <div class="col-md-4">
	        <div class="col-md-6">Pisos</div>
	        <select name="piso" id="id_piso" class="form-control form-control-sm">
	        	<option value="0"> --- </option>
	        	{% for item in pisos %}
	        		<option value="{{ item.id }}" data-chained="{{ item.edificio.id }}">{{ item.nombre }}</option>
	        	{% endfor%}
	        </select>
	    </div>
	     <div class="col-md-4">
	     	<div class="col-md-6">Salas</div>
	        <select name="sala" id="id_sala" class="form-control form-control-sm">
	        	<option value="0"> --- </option>
	        	{% for item in salas %}
	        		<option value="{{ item.id }}" data-chained="{{ item.piso.id }}">{{ item.nombre }} ({{ item.uso }})</option>
	        	{% endfor%}
	        </select>
	    </div>
	</div>
	<br />
	<!-- Fila 2 -->
	<div class="row">
	    <div class="col-md-4">
		 	<div class="col-md-6">Tipo</div>
	        <select name="tipo" id="id_tipo" class="form-control form-control-sm">
	        	<option value="0"> --- </option>
	        	{% for item in tipos %}
	        		<option value="{{ item.id }}">{{ item.nombre }}</option>
	        	{% endfor%}
	        </select>
	    </div>
	   	    <div class="col-md-5">
		     	<div class="col-md-7">Objeto</div>
		        <select name="objeto" id="id_objeto" class="form-control form-control-sm">
		        	<option value="0"> --- </option>
		        	{% for item in objetos %}
		        		<option value="{{ item.id }}" data-chained="{{ item.tipo.id }}">{{ item.nombre }}</option>
		        	{% endfor%}
		        </select>
		    	</div>
		    <div class="col-md-3">
		        <div class="col-md-4">{{ form.cantidad.label }}</div>
		        <input type="number" name="cantidad" class="form-control form-control-sm">
		    </div>
	</div>
	<br />
	<!-- Fila 3 -->
	<div class="row">
	 	<div class="col-md-12">
	        <div class="col-md-4">{{ form.observaciones.label }}</div>
	        <textarea name="observaciones" class="form-control form-control-sm"></textarea>
	    </div>
	</div>
		<br />
	<!-- Fila 4 -->
	<div class="row">
		<div class="col-md-12">

				<button type="submit" class=" form-control save btn btn-info">Guardar</button>
		</div>
	</div>
	</form>
</div>
<script>
	$(function() {
		$('#id_piso').chained('#id_edificio');
		$('#id_sala').chained('#id_piso');
		$('#id_objeto').chained('#id_tipo');
	});
</script>
{% endblock %}

inv/templates/asignacion_list.html
{% extends "base_generic.html" %}

{% block content %}

<div class="col-md-10 col-md-offset-1">
<table class="table table-striped table-hover table-condensed ">
	<legend>Asignaciones ingresadas</legend>
	<tr>
		<th>Sala</th>
		<th>Edificio</th>
		<th>Objeto</th>
		<th>Cantidad</th>
		<th>Observaciones</th>
	</tr>
	{% for a in asignaciones %}
		<tr>
			<td>{{ a.sala }}</td>
			<td>{{ a.edificio }}</td>
			<td>{{ a.objeto }}</td>
			<td>{{ a.cantidad }}</td>
			<td>{{ a.observaciones }}</td>
		</tr>
	{% endfor %}

</table>

</div>

{% endblock %}

inv/templates/base_generic.html
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% fontawesome_5_static %}
  {% block title %}<title>Inventario</title>{% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}" >
  <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
  <script src="{% static 'js/bootstrap-min.js' %}"></script>
</head>

<body>
  	<div class="container-fluid">
  		<div class="row">
  			<div class='col-md-10 col-md-offset-1'>
  	{% block sidebar %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'index' %}">
        <span>Inventario colegio Nahuelcura</span>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'asignacion_new' %}">Registrar articulo</a></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ver <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="{% url 'asignacion_list' %}">Ver asignaciones</a></li>
					<li><a href="{% url 'inventario' %}">Ver inventario</a></li>
					<li><a href="{% url 'salas_list' %}">Ver salas</a></li>
				</ul>
			</li>
								   
		</ul>

		<p class="navbar-text navbar-right">
	  		   {% if user.is_authenticated %}
					{% fa5_icon 'user' %} Hola, {{ user.get_username }} &nbsp;&nbsp; 
			     <a href="{% url 'logout'%}?next='/'" class="btn btn-danger btn-sm">{% fa5_icon 'times' %} &nbsp;Salir</a>
			   {% else %}
			     <a href="{% url 'login'%}?next={{request.path}}" class="btn btn-sm btn-success">{% fa5_icon 'user' %} &nbsp;Acceder</a>   
			   {% endif %} 
	  		
  		</p>
    </div>
  </div>

</nav>

  	

	{% endblock %}
  	{% block content %}<!-- default content text (typically empty) -->{% endblock %}
		</div></div>
	</div>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
	<script src="{% static 'js/jquery.chained.js' %}"></script>
	<script>

	
</script>
</body>
</html>

inv/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

<p>Esta es la pagina de inicio del inventario.</p>

{% endblock %}

inv/templates/inventario.html
{% extends "base_generic.html" %}

{% block content %}


<div class="col-md-6 col-md-offset-3">
<table class="table table-striped table-hover table-condensed ">
	<legend>Inventario general</legend>
	<tr>
		<th>Objeto</th>
		<th>Cantidad</th>
	</tr>
	{% for i in inventario %}
		<tr>
			<td><a href="{% url 'objeto_detail' pk=i.objeto__id %}">{{ i.objeto__nombre }}</a></td>
			<td>{{ i.total }}</td>
		</tr>
	{% endfor %}

</table>

</div>

{% endblock %}

inv/templates/objeto_detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2">

<h2>{{ objeto.nombre }}</h2>

<table class="table table-condensed table-bordered">
	<tr>
		<th>Tipo de objeto</th>
		<td>{{ objeto.tipo.nombre }}</td>
	</tr>
	<tr>
		<th>Clase de objeto</th>
		<td>{{ objeto.tipo.clase.nombre }}</td>
	</tr>
</table>

<div class='col-md-12'>
<table class="table table-striped table-hover table-condensed ">
	<legend>Distribución</legend>
	<tr>
		<th>Sala</th>
		<th>Cantidad</th>
		<th>Observaciones</th>
	</tr>
	{% for d in detalle %}
		<tr>
			<td>{{ d.sala.uso }}</td>
			<td>{{ d.cantidad }}</td>
			<td>{{ d.observaciones }}</td>
		</tr>
	{% endfor %}

</table>
</div>
</div>

{% endblock %}

inv/templates/sala_detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2">

<h2>{{ sala.uso }}</h2>

<table class="table table-condensed table-bordered">
	<tr>
		<th>Nombre de sala</th>
		<td>{{ sala.nombre }}</td>
	</tr>
	<tr>
		<th>Ubicación</th>
		<td>{{ sala.piso.nombre }} {{ sala.piso.edificio.nombre }}</td>
	</tr>
</table>

<div class='col-md-12'>
{% if detalle %}
	<table class="table table-striped table-hover table-condensed ">
		<legend>Inventario</legend>
		<tr>
			<th>Tipo</th>
			<th>Objeto</th>
			<th>Cantidad</th>
		</tr>
		{% for d in detalle %}
			<tr>
				<td>{{ d.tipo }}</td>
				<td>{{ d.objeto }}</td>
				<td>{{ d.cantidad }}</td>
			</tr>
		{% endfor %}
	</table>
{% else %}
	<span>No hay registros</span>
{% endif %}
</div>

</div>

{% endblock %}

inv/templates/salas_list.html
{% extends "base_generic.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2">
<table class="table table-stripped table-hover table-condensed ">
	<legend>Listado de salas</legend>
	<tr>
		<th>Uso</th>
		<th>Sala</th>
		<th>Edificio</th>
	</tr>
	{% for s in salas %}
		<tr>
			<td><a href="{% url 'sala_detail' pk=s.id %}">{{ s.uso }}</a></td>
			<td>{{ s.nombre }}</td>
			<td>{{ s.piso }}</td>
		</tr>
	{% endfor %}

</table>

</div>

{% endblock %}